name: slide_digital_clock
description: Digital Clock for Flutter
version: 0.0.1
author: Çağlar YILMAZ <caglarsibel.ylmz@gmail.com>
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter: